#!/usr/bin/env bash
# Made by mH (https://github.com/matthmr)

# Disk
DRIVE="/dev/sdb2"
DISK=$(df -H "$DRIVE" | sed 1d | awk '{print $3 "/" $2 " ["$5"]" " ["$6"]"}')

# Volume
VOL=$(amixer get Master | grep -Eo '\[[0-9]{1,3}%\] \[\-?[0-9]{1,3}\.[0-9]{1,2}dB')
DB=${VOL/\[*%\] /}
PERC=${VOL/$DB/}
PERC=${PERC/\[/}
PERC=${PERC/\]/}
VOL="$PERC$DB+]"

# Memory
MEM=$(free -h --si | awk '/^Mem:/ {print $3 "/" $2}')
_MEM=$(free --mega | awk '/^Mem:/ {print $2 "/" $3}')
PERC=$(( 100 / ($_MEM) ))
MEM="$MEM [$PERC%]"

# Ethernet
IP=$(ip addr show eth0 | grep 192\.168 | awk '{print $2}')
IP=${IP%/*}

# Uptime
UPTIME=$(uptime -p | grep -o '[0-9]*' | tr '\n' ':')
UPTIME=${UPTIME%:}

# Kernel
KERNEL=$(uname -r)
KERNEL=${KERNEL%-arch*}

# Time
DATE_DAY=$(date +'%d/%m/%Y %a')
DATE_HOUR=$(date +'%I:%M %p')

PROMPT=\
"  $KERNEL |\
  $IP |\
 墳 $VOL |\
  $MEM |\
  $DISK |\
  $UPTIME |\
  $DATE_DAY |\
  $DATE_HOUR "

echo "$PROMPT"
