#!/usr/bin/sh

# wit --help
# wit [-s dir]
# wit -s => wit -s .
# wit [-d dir]
# wit -d => wit -d .
# wit [-e dir]
# wit -e => wit -e .
# wit 'git repo' -p [dir]
# wit 'git repo' => wit 'git repo' -p .
# wit [-f file] [-p dir]
# wit [-f file] => wit [-f file] -p .

# Change the $EDITOR variable to the one of your desire
# Default is vim
EDITOR=vim

if [ $# == 0 ]; then
	# wit
	printf "\033[33mBad:\033[0m Bad usage. See wit --help.\n"
	exit 1
fi

if [ $# == 1 ]; then

	# wit --init

	# wit --help
	if [[ "$1" == '--help' ]]; then
		printf "\nMade by mH (https://www.github.com/observeofmath)
	\b WIT: What Is This\t=> A directory descriptor manager
	\nUsage:\twit [desc] [-p DIR]	=> Writes DESC to DIR
	wit [-s DIR]	\t=> Shows wit of DIR
	wit [-f FILE] [-p DIR]	=> Writes FILE to DIR
	wit [-d DIR]	\t=> Deletes wit of DIR
	wit [-e DIR]	\t=> Edits wit of DIR (editor set by the EDITOR variable at the script)
	\n"
		exit 0
	fi

	# wit -s 
	if [[ "$1" == '-s' ]]; then
		if test -f .wit; then
			printf "\033[32mOK:\033[0m wit of $PWD:\n"; printf "\n"
			cat ./.wit; printf "\n"
			exit 0

		# file not found
		else
			printf "\033[31mErr:\033[0m File does not exist\n"
			exit 127
		fi
	fi

	# wit -d
	if [[ "$1" == '-d' ]]; then
		if test -f .wit; then
			rm .wit
			printf "\033[32mOK:\033[0m wit of $PWD deleted\n"
			exit 0
		# file not found
		else
			printf "\033[31mErr:\033[0m File does not exist\n"
			exit 127
		fi
	fi

	# wit -e
	if [[ "$1" == '-e' ]]; then
		$EDITOR .wit
		exit 0
	fi

	printf "$1\n" > .wit
	printf "\033[32mOK:\033[0m Created identification file at .wit.\n"
	exit 0

fi

if [ $# == 2 ]; then

	# wit [-s DIR]
	if [[ "$1" == '-s' ]]; then
		if test -f $2/.wit; then
			printf "\033[32mOK:\033[0m wit of $2:\n"; printf "\n"
			cat $2/.wit; printf "\n"
			exit 0
		else
			printf "\033[31mErr:\033[0m File does not exist.\n"
			exit 127
		fi
	fi

	# wit [-f FILE]
	if [[ "$1" == '-f' ]]; then
		if test -f $2; then
			cat $2 > ./.wit
			printf "\033[32mOK:\033[0m Created identification file at .wit.\n"
			exit 0
		else
			printf "\033[31mErr:\033[0m File does not exist\n"
			exit 127	
		fi
	fi

	# wit [-d DIR]
	if [[ "$1" == '-d' ]]; then
		if test -f "$2/.wit"; then
			rm "$2/.wit"
			printf "\033[32mOK:\033[0m wit of $2/.wit deleted\n"
			exit 0
		else
			printf "\033[31mErr:\033[0m File does not exist\n"
			exit 127	
		fi
	fi

	# wit [-e dir]
	if [[ "$1" == '-e' ]]; then
		$EDITOR "$2/.wit"
		exit 0
	fi
fi

if [ $# == 3 ]; then 

	# wit [DESC] [-p DIR]
	if [[ "$2" == '-p' ]]; then
		printf "$1\n" > $3/.wit
		printf "\033[32mOK:\033[0m Created identification file at $3/.wit.\n"
		exit 0
	# wit ! ? !
	else
		printf "\033[33mBad:\033[0m Bad usage. See wit --help.\n"
		exit 1
	fi
fi

if [ $# == 4 ]; then

	# wit [-f FILE] [-p DIR]
	if [[ "$1" == '-f' ]]; then
		if [[ "$3" == '-p' ]]; then
			DEST=$4
			if test -f $2; then
				cat $2 > $DEST/.wit
				printf "\033[32mOK:\033[0m Created identification file at $DEST/.wit.\n"
				exit 0
			else
				printf "\033[31mErr:\033[0m File does not exist\n"
				exit 127
			fi
		# wit ! ! ? !
		else
			printf "\033[33mBad:\033[0m Bad usage. See wit --help.\n"
			exit 1
		fi
	# wit ? ! ! !
	else
		printf "\033[33mBad:\033[0m Bad usage. See wit --help.\n"
		exit 1
	fi
fi
